//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int PMS_ID { get; set; }
        public Nullable<int> PMS_code { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string paid { get; set; }
        public string Duration { get; set; }
        public Nullable<int> no_of_users { get; set; }
        public string PMS_Name { get; set; }
        public string owner_name { get; set; }
        public string Email { get; set; }
        public Nullable<int> City_id { get; set; }
        public string Phone { get; set; }
        public string address { get; set; }
    }
}
