//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_payments
    {
        public int accounts_payments_id { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> PayType_ID { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public string visa_chq_no { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
