//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int Booking_ID { get; set; }
        public Nullable<int> Property_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<System.DateTime> Planned_Arrival_Date { get; set; }
        public Nullable<System.DateTime> Planned_Departure_Date { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<decimal> Night_price { get; set; }
        public Nullable<int> Booking_source { get; set; }
        public Nullable<int> No_of_nights { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Property_Type_ID { get; set; }
        public Nullable<System.DateTime> Actual_arrival_Date { get; set; }
        public Nullable<System.DateTime> Actual_Departure_Date { get; set; }
        public bool Is_Cancelled { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public string Pay_Source_Type { get; set; }
        public bool IS_confirmed { get; set; }
        public Nullable<System.DateTime> confirmed_Date { get; set; }
        public string Property_Name { get; set; }
        public string Property_type_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<decimal> child_no { get; set; }
        public Nullable<decimal> person_no { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
    }
}
