//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int client_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Commission_discount { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> Clients_type_id { get; set; }
        public string code { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string contact_person_name { get; set; }
        public string person_email { get; set; }
        public string person_phone { get; set; }
        public string person_mob { get; set; }
        public string logo { get; set; }
    }
}
