//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_dtl
    {
        public int condition_id { get; set; }
        public Nullable<int> contract_id { get; set; }
        public string condition_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> PMS_ID { get; set; }
    }
}
