//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest
    {
        public int Guest_ID { get; set; }
        public string Guest_Name { get; set; }
        public string Guest_email { get; set; }
        public Nullable<int> Nationality_ID { get; set; }
        public Nullable<int> Identity_ID { get; set; }
        public bool Is_Black_listed { get; set; }
        public bool Is_Vip { get; set; }
        public string identity_type { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string gendre { get; set; }
        public string nickname { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> Booking_id { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Phone { get; set; }
        public string Mobil { get; set; }
        public string Company_Name { get; set; }
        public string Company_address { get; set; }
        public Nullable<int> Company_country { get; set; }
        public Nullable<int> Company_city { get; set; }
        public string Company_Mobil { get; set; }
        public string Company_phone { get; set; }
        public string guest_type { get; set; }
    }
}
