//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class housekeeping_trans
    {
        public int Trans_ID { get; set; }
        public Nullable<int> Property_ID { get; set; }
        public string Task { get; set; }
        public string Assign_to { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public string Property_Name { get; set; }
    }
}
