//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class identity_types
    {
        public int identity_ID { get; set; }
        public Nullable<int> Parent_identity_id { get; set; }
        public string identity_name { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
