//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int image_id { get; set; }
        public Nullable<int> PropertyType_ID { get; set; }
        public Nullable<int> Property_ID { get; set; }
        public string image1 { get; set; }
    }
}
