//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_dtl
    {
        public int invoice_no { get; set; }
        public int Invoice_dtl_id { get; set; }
        public int charge_id { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public int discount_percent { get; set; }
        public int discount_value { get; set; }
        public System.DateTime Charge_Date { get; set; }
        public int Booking_ID { get; set; }
        public int Property_ID { get; set; }
        public int Guest_ID { get; set; }
        public int Agent_ID { get; set; }
        public int user_id { get; set; }
        public int PMS_ID { get; set; }
        public string PMS_Name { get; set; }
    }
}
