//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_id { get; set; }
        public Nullable<System.DateTime> real_date { get; set; }
        public string action_cat { get; set; }
        public string action { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public string PMS_Name { get; set; }
        public Nullable<int> Bookibng_ID { get; set; }
    }
}
