//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messege
    {
        public int messege_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string messege_title { get; set; }
        public string messege_body { get; set; }
        public Nullable<System.DateTime> messege_date { get; set; }
        public Nullable<bool> flag_read { get; set; }
    }
}
