//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accounts_payments> accounts_payments { get; set; }
        public virtual DbSet<amenity> amenities { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<Booking_has_Property> Booking_has_Property { get; set; }
        public virtual DbSet<booking_source> booking_source { get; set; }
        public virtual DbSet<charge> charges { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<clients_type> clients_type { get; set; }
        public virtual DbSet<contract_dtl> contract_dtl { get; set; }
        public virtual DbSet<contracts_hdr> contracts_hdr { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<guest> guests { get; set; }
        public virtual DbSet<housekeeping_trans> housekeeping_trans { get; set; }
        public virtual DbSet<identity_types> identity_types { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<invoice_dtl> invoice_dtl { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<Messege> Messeges { get; set; }
        public virtual DbSet<nationality> nationalities { get; set; }
        public virtual DbSet<offer> offers { get; set; }
        public virtual DbSet<Offers_dtl> Offers_dtl { get; set; }
        public virtual DbSet<package_charges> package_charges { get; set; }
        public virtual DbSet<package_dtl> package_dtl { get; set; }
        public virtual DbSet<package_hdr> package_hdr { get; set; }
        public virtual DbSet<payment_types> payment_types { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<property_has_aminities> property_has_aminities { get; set; }
        public virtual DbSet<property_types> property_types { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<reply> replies { get; set; }
        public virtual DbSet<role_permissions> role_permissions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<season> seasons { get; set; }
        public virtual DbSet<seasons_rates> seasons_rates { get; set; }
        public virtual DbSet<status_color> status_color { get; set; }
        public virtual DbSet<status_types> status_types { get; set; }
        public virtual DbSet<system_options> system_options { get; set; }
        public virtual DbSet<Temp_charges> Temp_charges { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
