//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_dtl
    {
        public int trans_ID { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> Package_price { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> Property_type_id { get; set; }
        public string Property_type_name { get; set; }
        public Nullable<int> adults_no { get; set; }
        public Nullable<int> child_no { get; set; }
        public string name { get; set; }
        public Nullable<int> No_of_Days { get; set; }
        public Nullable<int> id_pack { get; set; }
    }
}
