//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_charges
    {
        public int trans_id { get; set; }
        public int Charge_ID { get; set; }
        public Nullable<decimal> Charge_Price { get; set; }
        public string name { get; set; }
        public Nullable<int> offer_id { get; set; }
        public string offer_name { get; set; }
        public Nullable<bool> is_selected { get; set; }
    }
}
