//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Payment_ID { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> payTime { get; set; }
        public string client_type { get; set; }
        public int Guest_ID { get; set; }
        public int visa_chq_no { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public int PMS_ID { get; set; }
        public int Booking_ID { get; set; }
        public int client_id { get; set; }
        public int Property_ID { get; set; }
        public int user_id { get; set; }
        public string receipt_type { get; set; }
        public string payment_type { get; set; }
    }
}
