//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_types
    {
        public int PropertyType_ID { get; set; }
        public string Property_type_name { get; set; }
        public int child_no { get; set; }
        public int adults_no { get; set; }
        public Nullable<decimal> price { get; set; }
        public int no_of_properties { get; set; }
        public int PMS_ID { get; set; }
        public int user_id { get; set; }
        public int start_number { get; set; }
        public string Name_char { get; set; }
        public bool is_active { get; set; }
        public bool type_view { get; set; }
        public string property_type_icon { get; set; }
    }
}
