//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int Property_ID { get; set; }
        public int Property_type_id { get; set; }
        public string Property_Name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public string house_keeping_status { get; set; }
        public string fixed_status { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> floor { get; set; }
    }
}
