//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_has_aminities
    {
        public int ID { get; set; }
        public Nullable<int> PropertyType_ID { get; set; }
        public Nullable<int> Amenity_ID { get; set; }
        public string Property_type_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_selected { get; set; }
    }
}
