//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seasons_rates
    {
        public int trans_id { get; set; }
        public int Property_type_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public int PMS_ID { get; set; }
        public int user_id { get; set; }
        public Nullable<int> id_season { get; set; }
        public string Property_type_name { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<int> adults_no { get; set; }
        public Nullable<int> child_no { get; set; }
        public string season_name { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
    }
}
