//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_color
    {
        public int status_id { get; set; }
        public string status_name { get; set; }
        public string status_color1 { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public string status_name_en { get; set; }
    }
}
