//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_options
    {
        public int PMS_ID { get; set; }
        public string Default_lang { get; set; }
        public Nullable<int> Default_currency { get; set; }
        public int no_of_decimals { get; set; }
        public string check_in_time { get; set; }
        public string check_out_time { get; set; }
        public Nullable<int> child_max_age { get; set; }
        public Nullable<int> infant_max_age { get; set; }
        public string Default_travel_agent_commission { get; set; }
        public string Default_company_Discount { get; set; }
        public string room_after_check_out { get; set; }
        public string room_after_change_room { get; set; }
        public string cancel_booking_min_fee { get; set; }
        public string cancel_booking_percent_fee { get; set; }
        public Nullable<int> cancel_booking_dayes { get; set; }
        public bool is_credit_card_needed { get; set; }
        public decimal si_deposit_needed { get; set; }
        public Nullable<int> early_checked_in_hours { get; set; }
        public Nullable<int> early_check_in_fixed_fee { get; set; }
        public Nullable<int> early_check_in_booking_percent { get; set; }
        public Nullable<int> early_check_in_night_percent { get; set; }
        public Nullable<int> early_check_out_dayes { get; set; }
        public Nullable<int> early_check_out_fixed_fee { get; set; }
        public Nullable<int> early_check_out_booking_percent { get; set; }
        public Nullable<int> early_check_out_night_percent { get; set; }
        public Nullable<int> late_check_out_hours { get; set; }
        public Nullable<int> late_check_out_fixed_fee { get; set; }
        public Nullable<int> late_check_out_booking_percent { get; set; }
        public Nullable<int> late_check_out_night_percent { get; set; }
        public string PMS_logo { get; set; }
        public int user_id { get; set; }
        public string PMS_Name { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string mob { get; set; }
    }
}
