//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> PMS_ID { get; set; }
        public string gendre { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> Nationality_ID { get; set; }
        public Nullable<int> Identity_ID { get; set; }
        public string identity_type { get; set; }
        public string email { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string phone { get; set; }
        public string mob { get; set; }
        public Nullable<System.DateTime> start_job_date { get; set; }
        public string confirm_password { get; set; }
        public string image { get; set; }
        public string vcode { get; set; }
    }
}
